# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3425b5791371701ac971c3662fc24afa8613a97bf94a3d43fec1fc1b8099e7f681ea331f835c0e9004e8c7ad0862351ab7f69d1125a15a697841ff8687ed89f9
  S3_KEY: AKIAJHRHR5TRCFNBUC4Q
  S3_SECRET: 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
test:
  secret_key_base: 661caba21df6e432f748d12fccd66848c413b2da4ac553cfd772a0fd38853e80f12ed29e4164aa6694134d4b796ef2a4aef07deb40ea290b4d0ee8fb250c8004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: ENV['S3_KEY']
  # S3_KEY: AKIAJHRHR5TRCFNBUC4Q
  secret_access_key: ENV['S3_SECRET']
  # S3_SECRET: 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
